[theme]
primaryColor = "#7C3AED"
backgroundColor = "#0F0F23"
secondaryBackgroundColor = "#1E1E3F"
textColor = "#FFFFFF"
font = "Poppins"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

# Custom CSS Injection
[client]
customTheme = true
