[theme]
# Base Theme
primaryColor = "#00AEEF"            # Accent (Electric Blue)
backgroundColor = "#0A0E1A"         # Main Background (Dark Navy)
secondaryBackgroundColor = "#111827" # Card / Panel Background
textColor = "#FFFFFF"               # White Text (Readable, Clean)
font = "Poppins"                    # Modern, clean sans-serif
