[theme]
primaryColor = "#00FFAA"                # Button / accent color (neon green)
backgroundColor = "#001A33"             # Main background (dark navy blue)
secondaryBackgroundColor = "#002B55"    # Boxes, sidebar background (medium blue)
textColor = "#FFFFFF"                   # White text for contrast
font = "sans serif"
