[firebase]
type = "your_type"
project_id = "your_project_id"
private_key_id = "your_private_key_id"
private_key = "your_private_key"
client_email = "your_client_email"
client_id = "your_client_id"
auth_uri = "your_auth_uri"
token_uri = "your_token_uri"
auth_provider_x509_cert_url = "your_auth_provider_url"
client_x509_cert_url = "your_client_cert_url"

# Optional services (app works without these)
[email]
EMAIL_ADDRESS = "your_email@gmail.com"
EMAIL_PASSWORD = "your_app_password"

[twilio]
ACCOUNT_SID = "your_twilio_account_sid"
AUTH_TOKEN = "your_twilio_auth_token"
PHONE_NUMBER = "+1234567890"
