[firebase]
type = "your_type"
project_id = "your_project_id"
private_key_id = "your_private_key_id"
private_key = "your_private_key"
client_email = "your_client_email"
client_id = "your_client_id"
auth_uri = "your_auth_uri"
token_uri = "your_token_uri"
auth_provider_x509_cert_url = "your_auth_provider_url"
client_x509_cert_url = "your_client_cert_url"

# Optional services (app works without these)
[email]
EMAIL_ADDRESS = "zada44919@gmail.com"
EMAIL_PASSWORD = "mrgklwomlcwwfxrd"

[twilio]
ACCOUNT_SID = "AC6de27fa2a826804c0b436d9a148308f3"
AUTH_TOKEN = "yf4136085598ae85701b0f41fae0dd9fe"
PHONE_NUMBER = "+923132766906"
